site_name: zmk-config
site_url: https://semi710.github.io/zmk-config
site_description: ZMK keyboard configs, built with nix
site_author: Nikhil Singh
repo_name: semi710/zmk-config
repo_url: https://github.com/semi710/zmk-config

theme:
  name: material
  font:
    text: Sora
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep orange
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Keyboards:
      - Corne: keyboards/corne.md
  - Flake Module: module.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/semi710/zmk-config
  generator: false

copyright: "Made with <span style=\"color: #ff6e40\">&hearts;</span> by Nikhil · <a href=\"https://semi.sh\">semi.sh</a>"
